### ISSUE TITLE
Endless running issue with different gradle version

### ISSUE THREAD

**Issue by MianChen** [CaelumF/FigmaToCompose#17]
Hi Caelum,

I am a Compose developer, who is also using Figma. Your plugin seems a game change for me. 

But when I tried, it couldn't run for me. I cloned the latest version and run with `./gradlew run --args="-config=application.conf"` on my Mac. But it failed either with `Could not initialize class org.codehaus.groovy.reflection.ReflectionCache`, or `Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`, until I updatd the gradle distribution from `gradle-6.2.2-bin` to `gradle-6.4.1-all`. 

But I got stuck again at 80% and it never went through as shown in the screenshot. I moved to the latest distribution, `gradle-7.0.2-all` and tried to rebuild, but still the same, running frozen at 80%.

<img width="485" alt="Screen Shot 2021-08-10 at 4 58 55 PM" src="https://user-images.githubusercontent.com/5120576/129115891-3afbd3d0-4523-47d7-9cee-fbdf6d6db93e.png">

Regards,
Matt

**Comment by CaelumF** [comment]
Hey Matt,

Thanks for trying the plugin and for sharing your issue / fix.

It looks like after you updated the version it works all good. The 80% executing is just what Gradle shows using the Application plugin, since Gradle is usually used just for building code, I believe the Application plugin just adds a final "build" stage that simply runs the application, so the progress bar will never complete even though it's running perfectly fine.

Try using the plugin while it's "EXECUTING" and let me know how well it works for you :)

I'll try and see if I get the same issue running that gradle version - I suspect it may be JDK related, but if updating seems to fix then I'll update it here to avoid issues for others.

**Comment by MianChen** [comment]
Hi Caelum,

Thanks for your reply. Yes, the plugin works when it is "executing". I tried it and generated the code successfully. 

I am using Compose 1.0.1. It seems there are quite a few mismatches, and most of the UI got converted to `Box` and `ConstraintLayout`, not `Column` and `Row`.  Are they known bugs? And are you thinking about upgrading the plugin to support Compose stable?

**Comment by MianChen** [comment]
Hi Caelum,

Thanks for your reply. Yes, the plugin works when it is "executing". I tried it and generated the code successfully. I am using Compose 1.0.1. It seems there are quite a few mismatches, and most of the UI got converted to `Box` and `ConstraintLayout`, no `Column` and `Row` at all.

**Comment by CaelumF** [comment]
Nice! The Columns and Rows should come from any auto-layouts. Are any auto-layouts not getting converted? Yes I do try to keep the plugin updated but I'm not always using Compose myself so I don't always notice when things are broken, if you could share the mismatches I'll fix them :)
